[package]
name = "mrs-codex"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "A tool to process TPTP files and store results in SQLite"

[dependencies]
mrs-tptp = { workspace = true }
mrs-core = { workspace = true }
mrs-cnf = { workspace = true }
mrs = { path = "../.." }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4.6", features = ["derive"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
walkdir = "2.5.0"
rayon = "1.12.0"
wait-timeout = "0.2.1"
regex = "1.13.1"
crossbeam-channel = "0.5.17"
shlex = "2.0.1"
sysinfo = "0.39.6"
tempfile = "3.27.0"
sha2 = { workspace = true }
