[package]
name = "mrs-codex"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "A tool to process TPTP files and store results in SQLite"

[dependencies]
mrs-tptp = { workspace = true }
mrs-core = { workspace = true }
mrs-cnf = { workspace = true }
mrs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
rusqlite = { workspace = true }
walkdir = { workspace = true }
rayon = { workspace = true }
wait-timeout = { workspace = true }
regex = { workspace = true }
crossbeam-channel = { workspace = true }
shlex = { workspace = true }
sysinfo = { workspace = true }
tempfile = { workspace = true }
sha2 = { workspace = true }
