[package]
name = "mrs-search"
version.workspace = true
edition.workspace = true
description = "Proof search engine with given-clause loop"
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mrs-core = { workspace = true }
mrs-calculus = { workspace = true }
mrs-index = { workspace = true }
varisat = { workspace = true }
crossbeam-channel = { workspace = true }
